### ISSUE TITLE
The mapping is broken in javascript Number math

### ISSUE THREAD

**Issue by strainer** [bfontaine/seedrand.js#1]
Hi, Im afraid the mapping formula used in this prng requires 64 bit Int math to work properly. Javascript math is done in 64 bit float which has only 2^53 bits of Integer precision, so values larger than 2^53 drop accuracy. This causes non random looking artifacts in the output and more visibly the stream gets stuck in a little 'walk' after about 100,000 iterations.

**Comment by bfontaine** [comment]
Thank you for the report! Do you have any suggestion?

**Comment by strainer** [comment]
You're welcome bfontaine. I dont know any efficient fix to make the original algorithm work in 64 bit float. It is quite badly broke since its period will be anything less than about 100,000 for a given seed.  
I've pushed an LCG algorithm with period 2^32 as a simple alternative. It is not a high quality prng, but its output 'looks' ok and is fast and simple for test purposes.

**Comment by bfontaine** [comment]
I pulled your PR, thanks again! :smile:

**Comment by strainer** [comment]
Welcome bfontaine - thankyou for my first patch :)
